apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: syn
  namespace: syn
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - ssh://git@github.com/projectsyn/test-cluster-catalog.git
