apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: metrics-server
  namespace: syn
spec:
  destination:
    namespace: syn-metrics-server-test
    server: https://kubernetes.default.svc
  project: syn
  source:
    path: manifests/metrics-server
    plugin:
      name: kapitan
    repoURL: ssh://git@github.com/projectsyn/test-cluster-catalog.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
