apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: resource-locker
  namespace: syn
spec:
  destination:
    namespace: syn-resource-locker
    server: https://kubernetes.default.svc
  project: syn
  source:
    directory:
      recurse: true
    path: manifests/resource-locker
    repoURL: ssh://git@github.com/projectsyn/test-cluster-catalog.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
