apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: metrics-server
    chart: metrics-server-2.11.1
    heritage: Tiller
    release: metrics-server
  name: system:metrics-server
  namespace: syn-metrics-server
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  verbs:
  - get
  - list
  - watch
