apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
    app: metrics-server
    chart: metrics-server-2.11.1
    heritage: Tiller
    release: metrics-server
  name: v1beta1.metrics.k8s.io
  namespace: syn-metrics-server
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: syn-metrics-server
  version: v1beta1
  versionPriority: 100
