apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: metrics-server
    chart: metrics-server-2.11.1
    heritage: Tiller
    release: metrics-server
  name: metrics-server
  namespace: syn-metrics-server
