apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: metrics-server
    chart: metrics-server-2.11.1
    heritage: Tiller
    release: metrics-server
  name: metrics-server-auth-reader
  namespace: syn-metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: syn-metrics-server
