apiVersion: v1
data:
  vault-agent-config.hcl: |
    exit_after_auth = false

    auto_auth {
        method "kubernetes" {
            config = {
                role = "syn-cluster"
                token_path = "/var/run/secrets/syn/token"
            }
        }
        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
                mode = 0644
            }
        }
    }
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: vault-agent-config
  name: vault-agent-config
  namespace: syn
