apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
  namespace: syn
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: argocd-repo-server
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/part-of: argocd
                topologyKey: kubernetes.io/hostname
              weight: 5
      automountServiceAccountToken: false
      containers:
        - command:
            - uid_entrypoint.sh
            - argocd-repo-server
            - --redis
            - argocd-redis:6379
          env:
            - name: HOME
              value: /home/argocd
          image: docker.io/argoproj/argocd:v1.8.7@sha256:ce34acd7bac34d5a4fdbf96faf11fa5e01a7f96a27041d4472ca498886000cbf
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?full=true
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 5
          name: argocd-repo-server
          ports:
            - containerPort: 8081
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/config/ssh
              name: ssh-known-hosts
            - mountPath: /app/config/tls
              name: tls-certs
            - mountPath: /app/config/gpg/source
              name: gpg-keys
            - mountPath: /app/config/gpg/keys
              name: gpg-keyring
            - mountPath: /usr/local/bin/kapitan
              name: kapitan-bin
              subPath: kapitan
            - mountPath: /home/argocd/
              name: vault-token
        - args:
            - agent
            - -config
            - /etc/vault/vault-agent-config.hcl
          env:
            - name: SKIP_SETCAP
              value: 'true'
            - name: VAULT_ADDR
              value: https://vault.example.com
          image: docker.io/vault:1.5.3@sha256:14c29a6810974d3611c578509ad9398cadf44e8f6fa354c7d1ced62b5f26d372
          imagePullPolicy: IfNotPresent
          name: vault-agent
          ports: []
          securityContext:
            runAsUser: 100
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: /var/run/secrets/syn/
              name: steward-token
            - mountPath: /etc/vault/
              name: vault-config
            - mountPath: /home/vault/
              name: vault-token
      initContainers:
        - command:
            - cp
            - -v
            - /usr/local/bin/kapitan
            - /custom-tools/
          image: docker.io/projectsyn/kapitan:v0.29.1@sha256:14f31adadb5d1a28fa097a98bb48bb5a2a0cc1fbaa6f3bcd915e8ba7cd016662
          imagePullPolicy: Always
          name: install-kapitan
          volumeMounts:
            - mountPath: /custom-tools
              name: kapitan-bin
      volumes:
        - configMap:
            name: argocd-ssh-known-hosts-cm
          name: ssh-known-hosts
        - configMap:
            name: argocd-tls-certs-cm
          name: tls-certs
        - configMap:
            name: argocd-gpg-keys-cm
          name: gpg-keys
        - emptyDir: {}
          name: gpg-keyring
        - emptyDir: {}
          name: kapitan-bin
        - emptyDir:
            medium: Memory
          name: vault-token
        - configMap:
            name: vault-agent-config
          name: vault-config
        - name: steward-token
          secret:
            secretName: steward
