apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: "- name: kapitan\n  generate:\n    command: [kapitan, refs,\
    \ --reveal, --refs-path, ../../refs/, --file, ./]\n"
  repositories: '- url: ssh://git@github.com/projectsyn/test-cluster-catalog.git'
  repository.credentials: "- url: ssh://git@\n  sshPrivateKeySecret:\n    name: argo-ssh-key\n\
    \    key: sshPrivateKey\n"
  resource.customizations: "admissionregistration.k8s.io/MutatingWebhookConfiguration:\n\
    \  ignoreDifferences: |\n    jsonPointers:\n      - /webhooks/0/clientConfig/caBundle\n\
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:\n  ignoreDifferences:\
    \ |\n    jsonPointers:\n      - /webhooks/0/clientConfig/caBundle\napiextensions.k8s.io/CustomResourceDefinition:\n\
    \  ignoreDifferences: |\n    jsonPointers:\n      - /status\n      - /spec/scope\n"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/part-of: argocd
    name: argocd-cm
  name: argocd-cm
  namespace: syn
